# Site settings
title: Incredible.AI
email: a141890@gmail.com
description: "Artificial Intelligence and BigData"
encoding: utf-8

baseurl: ""
url: "http://incredible.ai"

# twitter_username:
github_username:  AndersonJo


# Build settings
rouge: pygments
markdown: kramdown
permalink: pretty
