# Site settings
title: Anderson Jo 헤헤헤
email: a141890@gmail.com
description: "개발자 조창민입니다. Machine Learning, Python, Django, R, Android, AWS, Game Server, Startup 등등 다양한 경험을 갖고 있는 개발자 입니다."

baseurl: ""
url: "http://andersonjo.github.io/"

# twitter_username:
github_username:  AndersonJo


# Build settings
rouge: pygments
markdown: kramdown
permalink: pretty
