# Site settings
title: Anderson Jo Techs
email: a141890@gmail.com
description: "Machine Learning, Deep Learning, Python, R, Game Server, Data Analysis, AWS, Hadoop, Hortonworks HDP, Spark, Scala, GPU (CUDA), TensorFlow..."

baseurl: ""
url: "http://andersonjo.github.io/"

# twitter_username:
github_username:  AndersonJo


# Build settings
rouge: pygments
markdown: kramdown
permalink: pretty
