# Site settings
title: Anderson Jo
email: a141890@gmail.com
description: "Artificial Intelligence and BigData"

baseurl: ""
url: "http://andersonjo.github.io/"

# twitter_username:
github_username:  AndersonJo


# Build settings
rouge: pygments
markdown: kramdown
permalink: pretty
