# Site settings
title: "Incredible.AI"
email: "a141890@gmail.com"
description: "Artificial Intelligence and BigData"
encoding: utf-8

baseurl: ""
url: "http://incredible.ai"
exclude: ["_backups", "_site", ".git", ".idea"]


# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-numbered-headings

# twitter_username:
github_username:  AndersonJo


# Build settings
rouge: pygments
markdown: kramdown
permalink: pretty
